### ISSUE TITLE
Fail to invert bing.com

### ISSUE THREAD

**Issue by wander3** [Eliastik/page-shadow#2]
The background image on bing.com doesn't seem to invert with either "invert image" or the entire extension. If you could add a quick fix as a CSS rule to invert the page, which seems to work on the Stylish extension, that'd be great. Thanks.

**Comment by Eliastik** [comment]
Thanks for your report.

* Bug fixed: [commit](https://github.com/Eliastik/page-shadow/commit/725d610b046505bb85ac14f3aa311815736d7d54)
* I added a function to invert the entire pages, not only the images: [commit](https://github.com/Eliastik/page-shadow/commit/83142336f0276ec3fe93ced992bffb55f82c604a)

I will release a new version of the extension with these changes and with others bugfixes.
