### ISSUE TITLE
custom theme and available themes

### ISSUE THREAD

**Issue by rinaldi6109** [Eliastik/page-shadow#3]
Thank you for your addon which seems to be the lightest among the ones I've tried.
I don't understand why you have hard-coded all the theme settings but one. I'd like to have two or more custom themes to choose among, one dark and one light. I could hack the contents of .xpi file, replacing the settings of one or more of the 15 available themes, but so doing I will be forced to not update the addon...

**Comment by Eliastik** [comment]
I will try to add more custom themes slots (about 5) in a next version of the extension.

**Comment by Eliastik** [comment]
Multiple custom themes are now implemented by commits d8d6c56 and 877e70a. This new function will be available in the next version of the extension (2.7) which will be released soon.
